import json
import os
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from openai import OpenAI

from db.supabase import get_supabase

router = APIRouter()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


class BEFASTAssessment(BaseModel):
    balance: str
    eyes: str
    face: str
    arm: str
    speech: str
    symptom_onset: str
    patient_name: str
    patient_age: Optional[int] = None
    patient_id: Optional[str] = None


BEFAST_PROMPT = """You are a stroke triage AI assistant used in emergency settings.
Analyze the BEFAST symptom assessment and return ONLY valid JSON:
{
  "risk_level": "High|Medium|Low",
  "risk_score": 0,
  "positive_indicators": ["symptom name", ...],
  "immediate_actions": ["action 1", "action 2", ...],
  "clinical_notes": "2-3 sentence clinical assessment and rationale",
  "time_critical": true
}
Rules:
- High (risk_score 3-5): Any 3+ positive symptoms, OR face+arm+speech combination (classic stroke triad)
- Medium (risk_score 1-2): 1-2 positive symptoms
- Low (risk_score 0): All no/unsure
- time_critical = true if High or symptom_onset < 4.5 hours (thrombolysis window)
- immediate_actions for High MUST start with "Call 911 immediately" """


@router.post("/emergency/assess")
def assess_befast(assessment: BEFASTAssessment):
    symptoms = {
        "Balance loss": assessment.balance,
        "Sudden vision change (Eyes)": assessment.eyes,
        "Face drooping": assessment.face,
        "Arm weakness": assessment.arm,
        "Speech difficulty": assessment.speech,
    }
    symptom_text = "\n".join(f"  {k}: {v}" for k, v in symptoms.items())

    context = f"""
Patient: {assessment.patient_name}, Age: {assessment.patient_age or 'Unknown'}
Symptom onset: {assessment.symptom_onset}

BEFAST Assessment Results:
{symptom_text}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": BEFAST_PROMPT},
            {"role": "user", "content": context},
        ],
        temperature=0,
        max_tokens=500,
    )

    return json.loads(response.choices[0].message.content)


@router.post("/emergency/packet/{patient_id}")
def generate_packet(patient_id: str):
    supabase = get_supabase()

    patient = supabase.table("patients").select("*").eq("id", patient_id).execute()
    if not patient.data:
        raise HTTPException(404, "Patient not found")

    extracted = (
        supabase.table("extracted_info")
        .select("*")
        .eq("patient_id", patient_id)
        .execute()
    )

    p = patient.data[0]
    info = extracted.data[0] if extracted.data else {}

    packet = f"""
╔══════════════════════════════════════════════════════════════════╗
           EMERGENCY NEUROLOGIST HANDOFF PACKET — ClinIQ
╚══════════════════════════════════════════════════════════════════╝

PATIENT DEMOGRAPHICS
────────────────────
Name:              {p.get('name', 'Unknown')}
Age:               {p.get('age', 'Unknown')}
Gender:            {p.get('gender', 'Unknown')}
Medical Specialty: {p.get('medical_specialty', 'Unknown')}

ACTIVE DIAGNOSES
────────────────────
{chr(10).join(f'• {d}' for d in (info.get('diagnoses') or ['None documented']))}

CURRENT MEDICATIONS
────────────────────
{chr(10).join(f'• {m}' for m in (info.get('medications') or ['None documented']))}

⚠ ALLERGIES — CRITICAL
────────────────────
{chr(10).join(f'• {a}' for a in (info.get('allergies') or ['No known allergies']))}

RECENT LAB RESULTS
────────────────────
{chr(10).join(f'• {lr.get("test", "?")} : {lr.get("value", "?")} {lr.get("unit", "")} ({lr.get("date", "")})' for lr in (info.get('lab_results') or [])) or '• No lab results on record'}

CLINICAL SUMMARY
────────────────────
{info.get('summary_text', 'No summary available.')}

════════════════════════════════════════════════════════════════════
Generated by ClinIQ Clinical Intelligence Platform
Patient ID: {patient_id}
════════════════════════════════════════════════════════════════════
""".strip()

    return {"packet_text": packet, "patient_name": p.get("name", "Unknown")}
